# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('title',), 'permissions': (('can_view_conversation', 'Can view conversation'),), 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_at',), 'permissions': (('can_view_messages', 'Can view messages'),), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
