# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Tech code'),
        ),
    ]
