# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Map point title')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='map_attachments/%Y_%m_%d',
                                                verbose_name='Attachment')),
                ('devices', models.ManyToManyField(db_table='dot_device', to='devapp.Device', verbose_name='Devices')),
            ],
            options={
                'verbose_name': 'Map point',
                'verbose_name_plural': 'Map points',
                'db_table': 'dots',
                'permissions': (('can_view', 'Can view'),),
            },
        ),
    ]
