# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0004_auto_20171103_0006'),
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dot',
            options={'permissions': (('can_view', 'Can view'),), 'verbose_name': 'Map dot', 'verbose_name_plural': 'Map dots'},
        ),
        migrations.AddField(
            model_name='dot',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='map_attachments/%Y_%m_%d', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='dot',
            name='devices',
            field=models.ManyToManyField(db_table='dot_device', to='devapp.Device', verbose_name='Devices'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Map point title'),
        ),
    ]
