# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dot',
            options={'ordering': ('title',), 'permissions': (('can_view', 'Can view'),), 'verbose_name': 'Map point', 'verbose_name_plural': 'Map points'},
        ),
    ]
