# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_squashed_0003_auto_20180425_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseaccount',
            options={'ordering': ('username',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('fio',), 'permissions': (('can_view_userprofile', 'Can view staff profile'),), 'verbose_name': 'Staff account profile', 'verbose_name_plural': 'Staff account profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
