# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='ex@host.loc', max_length=254),
            preserve_default=False,
        ),
    ]
