# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_auto_20180413_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseaccount',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^(\\+[7,8,9,3]\\d{10,11})?$')], verbose_name='Telephone'),
        ),
    ]
