# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts_app', '0002_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skype',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(max_length=16,
                                   validators=[django.core.validators.RegexValidator('^\\+[7,8,9,3]\\d{10,11}$')],
                                   verbose_name='Telephone number'),
        ),
    ]
