# Generated by Django 2.1.3 on 2018-12-24 15:52

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_new_user_profile_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flags',
            field=bitfield.models.BitField((('notify_task', 'Notification about tasks'), ('notify_msg', 'Notification about messages'), ('notify_mon', 'Notification from monitoring')), default=0, verbose_name='Flags'),
        ),
    ]
