# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 10:16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_auto_20161206_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='admin@example.ru', max_length=254),
        ),
    ]
