# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message history',
                'verbose_name_plural': 'Message histories',
                'db_table': 'chat_message_history',
            },
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('status', models.CharField(choices=[('n', 'New'), ('r', 'Read')], default='n', max_length=1,
                                            verbose_name='Status of message')),
                ('tag', models.CharField(default='none', max_length=6, verbose_name='App tag')),
                ('target_employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Target employee')),
            ],
            options={
                'verbose_name': 'Message queue',
                'verbose_name_plural': 'Message queue',
                'db_table': 'chat_message_queue',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(default=0, verbose_name='Telegram chat id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Telegram bot',
                'verbose_name_plural': 'Telegram bots',
                'db_table': 'chat_telegram_bot',
            },
        ),
    ]
