# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-14 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('status', models.CharField(choices=[('n', 'New'), ('r', 'Read')], default='n', max_length=1, verbose_name='Status of message')),
                ('tag', models.CharField(default='none', max_length=6, verbose_name='App tag')),
                ('target_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Target employee')),
            ],
            options={
                'verbose_name': 'Message queue',
                'verbose_name_plural': 'Message queue',
                'db_table': 'chat_message_queue',
            },
        ),
        migrations.AlterModelOptions(
            name='messagehistory',
            options={'verbose_name': 'Message history', 'verbose_name_plural': 'Message histories'},
        ),
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'verbose_name': 'Telegram bot', 'verbose_name_plural': 'Telegram bots'},
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='chat_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Telegram chat id'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterModelTable(
            name='messagehistory',
            table='chat_message_history',
        ),
        migrations.AlterModelTable(
            name='telegrambot',
            table='chat_telegram_bot',
        ),
    ]
