# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='heigt', upload_to='', width_field='wdth')),
                ('wdth', models.PositiveSmallIntegerField(blank=True, default='759', editable=False, null=True)),
                ('heigt', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
