# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 23:51

from django.db import migrations, models
import django.db.models.deletion

import mydefs


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', mydefs.MyGenericIPAddressField(max_length=8, protocol='ipv4')),
                ('comment', models.CharField(max_length=256)),
                ('devtype',
                 models.CharField(choices=[('Dl', "Свич D'Link")], default='Dl', max_length=2)),
                ('man_passw', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=0)),
                ('speed',
                 models.CharField(choices=[('h', '100Mbps'), ('k', '1Gbps'), ('d', '10Gbps')], default='h',
                                  max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.Device')),
            ],
        ),
        migrations.CreateModel(
            name='PortStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_json_info', models.TextField()),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devapp.Port')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('device', 'num')},
        ),
    ]
