# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djing.fields
import mydefs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', mydefs.MyGenericIPAddressField(max_length=8, protocol='ipv4')),
                ('comment', models.CharField(max_length=256)),
                ('devtype', models.CharField(choices=[('Dl', "Свич D'Link")], default='Dl', max_length=2)),
                ('man_passw', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.CharField(choices=[('h', '100Mbps'), ('k', '1Gbps'), ('d', '10Gbps')], default='h', max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.Device')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together=set([('device', 'num')]),
        ),
        migrations.AlterModelTable(
            name='device',
            table='dev',
        ),
        migrations.AlterModelTable(
            name='port',
            table='dev_port',
        ),
        migrations.AddField(
            model_name='device',
            name='map_dot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapapp.Dot'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devtype',
            field=models.CharField(choices=[('Dl', 'DLink switch'), ('Pn', 'PON OLT')], default='Dl', max_length=2),
        ),
        migrations.RemoveField(
            model_name='port',
            name='speed',
        ),
        migrations.AddField(
            model_name='device',
            name='mac_addr',
            field=djing.fields.MACAddressField(blank=True, integer=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='parent_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devapp.Device'),
        ),
        migrations.AddField(
            model_name='port',
            name='descr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='devtype',
            field=models.CharField(choices=[('Dl', 'DLink switch'), ('Pn', 'PON OLT'), ('On', 'PON ONU')], default='Dl', max_length=2),
        ),
        migrations.AlterField(
            model_name='device',
            name='devtype',
            field=models.CharField(choices=[('Dl', 'DLink switch'), ('Pn', 'PON OLT'), ('On', 'PON ONU'), ('Ex', 'Eltex switch')], default='Dl', max_length=2),
        ),
    ]
