# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 13:18
from __future__ import unicode_literals

from django.db import migrations
import mydefs


class Migration(migrations.Migration):
    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id'], 'permissions': (('can_view_device', 'Can view device'),),
                     'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=mydefs.MyGenericIPAddressField(blank=True, max_length=8, null=True, protocol='ipv4',
                                                 verbose_name='Ip address'),
        ),
    ]
