# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0001_squashed_0022_auto_20170816_1109'),
        ('devapp', '0001_squashed_0007_auto_20170816_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonGroup'),
        ),
    ]
