# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='dev',
        ),
        migrations.AlterModelTable(
            name='port',
            table='dev_port',
        ),
    ]
