# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 22:03
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
        ('devapp', '0002_auto_20160909_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='map_dot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapapp.Dot'),
        ),
    ]
