# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djing.fields
import mydefs


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0003_auto_20170927_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='map_dot',
        ),
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.CharField(max_length=256, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='device',
            name='devtype',
            field=models.CharField(choices=[('Dl', 'DLink switch'), ('Pn', 'PON OLT'), ('On', 'PON ONU'), ('Ex', 'Eltex switch')], default='Dl', max_length=2, verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=mydefs.MyGenericIPAddressField(max_length=8, protocol='ipv4', verbose_name='Ip address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_addr',
            field=djing.fields.MACAddressField(blank=True, integer=True, null=True, unique=True, verbose_name='Mac address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='man_passw',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='SNMP password'),
        ),
        migrations.AlterField(
            model_name='device',
            name='parent_dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devapp.Device', verbose_name='Parent device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonGroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='port',
            name='descr',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='port',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.Device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='port',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number'),
        ),
    ]
