# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0004_device_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devtype',
            field=models.CharField(choices=[('Dl', 'DLink switch'), ('Pn', 'PON ONU')], default='Dl', max_length=2),
        ),
    ]
