# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0004_auto_20171103_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmp_item_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
