# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0005_device_snmp_item_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['comment'], 'permissions': (('can_view_device', 'Can view device'),), 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AddField(
            model_name='device',
            name='is_noticeable',
            field=models.BooleanField(default=False, verbose_name='Send notify when monitoring state changed'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('und', 'Undefined'), ('up', 'Up'), ('unr', 'Unreachable'), ('dwn', 'Down')], default='und', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='device',
            name='snmp_item_num',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='SNMP Number'),
        ),
    ]
