# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 07:18
from __future__ import unicode_literals

import taskapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devapp', '0002_auto_20160909_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=128)),
                ('priority', models.CharField(choices=[(b'A', '\u0412\u044b\u0441\u0448\u0438\u0439'), (b'B', '\u0412\u044b\u0448\u0435 \u0441\u0440\u0435\u0434\u043d\u0435\u0433\u043e'), (b'C', '\u0421\u0440\u0435\u0434\u043d\u0438\u0439'), (b'D', '\u041d\u0438\u0436\u0435 \u0441\u0440\u0435\u0434\u043d\u0435\u0433\u043e'), (b'E', '\u041d\u0438\u0437\u043a\u0438\u0439')], default=b'C', max_length=1)),
                ('out_date', models.DateField(blank=True, default=taskapp.models._delta_add_days, null=True)),
                ('time_of_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev', to='devapp.Device')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
