# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('S', 'Новая'), ('C', 'На выполнении'), ('F', 'Выполнена')], default='S', max_length=1),
        )
    ]
