# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[(b'S', '\u041d\u043e\u0432\u0430\u044f'), (b'C', '\u041d\u0430 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0438'), (b'F', '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0430')], default=b'S', max_length=1),
        )
    ]
