# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20161130_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mode',
            field=models.CharField(choices=[('na', 'не выбрано'), ('yt', 'жёлтый треугольник'), ('rc', 'красный крестик'), ('ls', 'слабая скорость'), ('cf', 'обрыв кабеля'), ('cn', 'подключение'), ('pf', 'переодическое пропадание'), ('cr', 'настройка роутера'), ('ot', 'другое')], default='na', max_length=2),
        )
    ]
