# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_auto_20161216_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-id',), 'permissions': (('can_viewall', 'Доступ ко всем задачам'), ('can_remind', 'Напоминания о задачах'))},
        ),
        migrations.AlterField(
            model_name='changelog',
            name='act_type',
            field=models.CharField(choices=[('e', 'Изменение задачи'), ('c', 'Создание задачи'), ('d', 'Удаление задачи'), ('f', 'Завершение задачи'), ('b', 'Задача начата')], max_length=1),
        ),
    ]
