# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_auto_20161218_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='act_type',
            field=models.CharField(choices=[(b'e', '\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438'), (b'c', '\u0421\u043e\u0437\u0434\u0430\u043d\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438'), (b'd', '\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438'), (b'f', '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438'), (b'b', '\u0417\u0430\u0434\u0430\u0447\u0430 \u043d\u0430\u0447\u0430\u0442\u0430')], max_length=1),
        ),
    ]
