# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
