# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djing.fields
import ip_pool.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_app', '0002_group_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpLeaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='Ip address')),
                ('mac_addr', djing.fields.MACAddressField(blank=True, integer=True, null=True, unique=True, verbose_name='Mac address')),
                ('lease_time', models.DateTimeField(auto_now_add=True, verbose_name='Lease time')),
                ('is_dynamic', models.BooleanField(default=False, verbose_name='Is dynamic')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('device_info', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Employed ip',
                'verbose_name_plural': 'Employed ip addresses',
                'db_table': 'ip_pool_employed_ip',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', ip_pool.fields.GenericIpAddressWithPrefix(help_text='Ip address of network. For example: 192.168.1.0 or fde8:6789:1234:1::', unique=True, verbose_name='IP network')),
                ('kind', models.CharField(choices=[('inet', 'Internet'), ('guest', 'Guest'), ('trust', 'Trusted'), ('device', 'Devices'), ('admin', 'Admin')], default='guest', max_length=6, verbose_name='Kind of network')),
                ('description', models.CharField(max_length=64, verbose_name='Description')),
                ('ip_start', models.GenericIPAddressField(verbose_name='Start work ip range')),
                ('ip_end', models.GenericIPAddressField(verbose_name='End work ip range')),
                ('groups', models.ManyToManyField(to='group_app.Group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
                'db_table': 'ip_pool_network',
                'ordering': ('network',),
            },
        ),
        migrations.AddField(
            model_name='ipleasemodel',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_pool.NetworkModel', verbose_name='Parent network'),
        ),
        migrations.AlterUniqueTogether(
            name='ipleasemodel',
            unique_together={('ip', 'network')},
        ),
    ]
