# Generated by Django 2.1 on 2018-10-05 15:17

from django.db import migrations
import djing.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ip_pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipleasemodel',
            name='mac_addr',
            field=djing.fields.MACAddressField(blank=True, integer=True, null=True, verbose_name='Mac address'),
        ),
        migrations.AlterUniqueTogether(
            name='ipleasemodel',
            unique_together={('ip', 'network', 'mac_addr')},
        ),
    ]
