# Generated by Django 2.1 on 2018-10-11 11:55

from django.db import migrations, models
import djing.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ip_pool', '0002_change_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Ip address')),
                ('lease_time', models.DateTimeField(auto_now_add=True, verbose_name='Lease time')),
                ('mac_addr', djing.fields.MACAddressField(blank=True, integer=True, null=True, verbose_name='Mac address')),
            ],
            options={
                'verbose_name': 'History lease',
                'verbose_name_plural': 'Leases history',
                'db_table': 'ip_pool_leases_history',
                'ordering': ('-lease_time',),
            },
        ),
        migrations.RemoveField(
            model_name='ipleasemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ipleasemodel',
            name='is_dynamic',
        ),
    ]
