# Generated by Django 2.1.1 on 2019-03-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_pool', '0003_auto_20181019_1230'),
    ]

    operations = [
        migrations.DeleteModel(name='IpLeaseModel'),
        migrations.DeleteModel(name='LeasesHistory')
    ]
