# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('speedIn', models.FloatField(default=0.0)),
                ('speedOut', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('time_of_action', models.IntegerField(default=30)),
                ('calc_type', models.CharField(choices=[('Df', 'Базовый расчётный функционал'),
                                                        ('Dp', 'Как в IS'),
                                                        ('Cp', 'Пользовательский')],
                                               default='Df', max_length=2)),
            ],
        ),
    ]
