# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicpay',
            options={'ordering': ('-id',), 'permissions': (('can_view_periodic_pay', 'Can view periodic pay'),), 'verbose_name': 'Periodic pay', 'verbose_name_plural': 'Periodic pays'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('title',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='tariff',
            name='calc_type',
            field=models.CharField(choices=[('Df', 'Base calculate functionality'), ('Dp', 'IS'), ('Cp', 'Private service'), ('Dl', 'IS Daily service')], default='Df', max_length=2, verbose_name='Script'),
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('speedIn', 'speedOut', 'amount', 'calc_type')},
        ),
    ]
