# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='descr',
            field=models.CharField(default='Descr', max_length=256),
            preserve_default=False,
        ),
    ]
