# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0002_tariff_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
