# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0003_tariff_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='time_of_action',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='calc_type',
            field=models.CharField(choices=[('Df', 'Базовый расчётный функционал'), ('Dp', 'Как в IS'), ('Cp', 'Для внутреннего пользования')], default='Df', max_length=2),
        ),
    ]
