# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0005_auto_20170502_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Periodic pay name')),
                ('when_add', models.DateTimeField(auto_now_add=True, verbose_name='When pay created')),
                ('calc_type', models.CharField(choices=[('df', 'Default periodic pay'), ('cs', 'Custom periodic pay')], default='df', max_length=2, verbose_name='Script type for calculations')),
                ('amount', models.FloatField(verbose_name='Total amount')),
                ('extra_info', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Periodic pay',
                'verbose_name_plural': 'Periodic pays',
                'db_table': 'periodic_pay',
                'ordering': ['-id'],
                'permissions': (('can_view_periodic_pay', 'Can view periodic pay'),),
            },
        ),
        migrations.AlterField(
            model_name='tariff',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='calc_type',
            field=models.CharField(choices=[('Df', 'Base calculate functionality'), ('Dp', 'IS'), ('Cp', 'Private service')], default='Df', max_length=2, verbose_name='Script'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='descr',
            field=models.CharField(max_length=256, verbose_name='Service description'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Tech service'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='speedIn',
            field=models.FloatField(default=0.0, verbose_name='Speed In'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='speedOut',
            field=models.FloatField(default=0.0, verbose_name='Speed Out'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Service title'),
        ),
    ]
