# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0006_auto_20180122_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelTable(
            name='tariff',
            table='tariffs',
        ),
    ]
