# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsteriskCDR',
            fields=[
                ('calldate', models.DateTimeField(default='0000-00-00 00:00:00', primary_key=True, serialize=False)),
                ('clid', models.CharField(default='', max_length=80)),
                ('src', models.CharField(default='', max_length=80)),
                ('dst', models.CharField(default='', max_length=80)),
                ('dcontext', models.CharField(default='', max_length=80)),
                ('channel', models.CharField(default='', max_length=80)),
                ('dstchannel', models.CharField(default='', max_length=80)),
                ('lastapp', models.CharField(default='', max_length=80)),
                ('lastdata', models.CharField(default='', max_length=80)),
                ('duration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(default=0)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('answer', models.DateTimeField(blank=True, default=None, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('disposition', models.CharField(choices=[('NO ANSWER', 'No answer'), ('FAILED', 'Failed'), ('BUSY', 'Busy'), ('ANSWERED', 'Answered'), ('UNKNOWN', 'Unknown')], default='', max_length=45)),
                ('amaflags', models.IntegerField(default=0)),
                ('accountcode', models.CharField(default='', max_length=20)),
                ('userfield', models.CharField(default='', max_length=255)),
                ('uniqueid', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'cdr',
            },
        ),
    ]
