# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asteriskcdr',
            options={'managed': False, 'ordering': ('-calldate',)},
        ),
        migrations.AlterModelOptions(
            name='smsmodel',
            options={'ordering': ('-when',), 'permissions': (('can_view_sms', 'Can view sms'),), 'verbose_name': 'SMS', 'verbose_name_plural': 'SMS'},
        ),
        migrations.AlterModelOptions(
            name='smsout',
            options={'ordering': ('-when',), 'permissions': (('can_view_sms', 'Can view sms'), ('can_send_sms', 'Can send sms')), 'verbose_name': 'Out SMS', 'verbose_name_plural': 'Out SMS'},
        ),
    ]
