# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-29 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('who', models.CharField(max_length=32)),
                ('dev', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
                'db_table': 'sms',
                'permissions': (('can_view_sms', 'Can view sms'),),
            },
        ),
        migrations.AlterModelOptions(
            name='asteriskcdr',
            options={'managed': False},
        ),
    ]
