# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True, verbose_name='Title')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Ip address')),
                ('ip_port', models.PositiveSmallIntegerField(verbose_name='Port')),
                ('auth_login', models.CharField(max_length=64, verbose_name='Login')),
                ('auth_passw', models.CharField(max_length=127, verbose_name='Password')),
                ('nas_type', models.CharField(choices=[('mktk', 'Mikrotik NAS')], default='mktk', max_length=4, verbose_name='Type')),
                ('default', models.BooleanField(default=False, verbose_name='Is default')),
            ],
            options={
                'verbose_name': 'Network access server. Gateway',
                'verbose_name_plural': 'Network access servers. Gateways',
                'db_table': 'nas',
                'ordering': ('ip_address',),
                'permissions': (('can_view_nas', 'Can view NAS'),),
            },
        ),
    ]
