# Generated by Django 2.1 on 2018-11-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw_app', '0002_auto_20181101_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasmodel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
