# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 23:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ip_pool', '0001_initial'),
        ('tariff_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abon',
            fields=[
                ('userprofile_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ballance', models.FloatField(default=0.0, validators=[django.core.validators.DecimalValidator])),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'abonent',
            },
            bases=('accounts_app.userprofile',),
        ),
        migrations.CreateModel(
            name='AbonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'abonent_groups',
            },
        ),
        migrations.CreateModel(
            name='AbonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('comment', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('abon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                             to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'abonent_log',
            },
        ),
        migrations.CreateModel(
            name='AbonTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_priority', models.PositiveSmallIntegerField(default=0)),
                ('time_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('abon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkto_tariff',
                                             to='tariff_app.Tariff')),
            ],
            options={
                'ordering': ('tariff_priority',),
                'db_table': 'abonent_tariff',
            },
        ),
        migrations.CreateModel(
            name='InvoiceForPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0)),
                ('comment', models.CharField(max_length=128)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_pay', models.DateTimeField(blank=True, null=True)),
                ('abon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                             to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_create',),
                'db_table': 'abonent_inv_pay',
            },
        ),
        migrations.AddField(
            model_name='abon',
            name='current_tariffs',
            field=models.ManyToManyField(through='abonapp.AbonTariff', to='tariff_app.Tariff'),
        ),
        migrations.AddField(
            model_name='abon',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='abonapp.AbonGroup'),
        ),
        migrations.AddField(
            model_name='abon',
            name='ip_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='ip_pool.IpPoolItem'),
        ),
        migrations.AlterUniqueTogether(
            name='abontariff',
            unique_together=set([('abon', 'tariff', 'tariff_priority')]),
        ),
    ]
