# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abongroup',
            name='address',
        ),
        migrations.AlterField(
            model_name='abongroup',
            name='title',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
