# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 12:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0001_squashed_0022_auto_20170816_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTelephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+[7,8,9,3]\\d{10,11}$')], verbose_name='Телефон')),
                ('owner_name', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name': 'Дополнительный телефон',
                'verbose_name_plural': 'Дополнительные телефоны',
                'db_table': 'additional_telephones',
                'ordering': ('owner_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='abon',
            options={'permissions': (('can_buy_tariff', 'Покупка тарифа абоненту'), ('can_view_passport', 'Может просматривать паспортные данные')), 'verbose_name': 'Абонент', 'verbose_name_plural': 'Абоненты'},
        ),
        migrations.AlterModelOptions(
            name='abongroup',
            options={'permissions': (('can_add_ballance', 'Пополнение счёта'),), 'verbose_name': 'Группа абонентов', 'verbose_name_plural': 'Группы абонентов'},
        ),
        migrations.AlterModelOptions(
            name='abonstreet',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AlterModelOptions(
            name='abontariff',
            options={'permissions': (('can_complete_service', 'Снятие со счёта средств'),), 'verbose_name': 'Услуга абонента', 'verbose_name_plural': 'Услуги абонентов'},
        ),
        migrations.AddField(
            model_name='additionaltelephone',
            name='abon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_telephones', to='abonapp.Abon'),
        ),
    ]
