# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 19:14
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abonapp', '0002_auto_20161206_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='abongroup',
            name='profiles',
            field=models.ManyToManyField(related_name='abon_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
