# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw_app', '0001_initial'),
        ('abonapp', '0002_auto_20180808_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='abon',
            name='nas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gw_app.NASModel', verbose_name='Network access server'),
        ),
    ]
