# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0006_auto_20180122_1732'),
        ('abonapp', '0003_auto_20170927_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicPayForId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pay', models.DateTimeField(blank=True, null=True, verbose_name='Last pay time')),
                ('next_pay', models.DateTimeField(verbose_name='Next time to pay')),
            ],
            options={
                'db_table': 'periodic_pay_for_id',
            },
        ),
        migrations.AlterModelOptions(
            name='abon',
            options={'ordering': ['fio'], 'permissions': (('can_buy_tariff', 'Buy service perm'), ('can_view_passport', 'Can view passport'), ('can_add_ballance', 'fill account'), ('can_ping', 'Can ping')), 'verbose_name': 'Abon', 'verbose_name_plural': 'Abons'},
        ),
        migrations.AlterModelOptions(
            name='abongroup',
            options={'ordering': ['title'], 'permissions': (('can_view_abongroup', 'Can view subscriber group'),), 'verbose_name': 'Abon group', 'verbose_name_plural': 'Abon groups'},
        ),
        migrations.AlterModelOptions(
            name='abonlog',
            options={'ordering': ['-date'], 'permissions': (('can_view_abonlog', 'Can view subscriber logs'),)},
        ),
        migrations.AlterModelOptions(
            name='abonstreet',
            options={'ordering': ['name'], 'verbose_name': 'Street', 'verbose_name_plural': 'Streets'},
        ),
        migrations.AlterModelOptions(
            name='abontariff',
            options={'ordering': ['time_start'], 'permissions': (('can_complete_service', 'finish service perm'),), 'verbose_name': 'Abon service', 'verbose_name_plural': 'Abon services'},
        ),
        migrations.AlterModelOptions(
            name='additionaltelephone',
            options={'ordering': ('owner_name',), 'permissions': (('can_view_additionaltelephones', 'Can view additional telephones'),), 'verbose_name': 'Additional telephone', 'verbose_name_plural': 'Additional telephones'},
        ),
        migrations.AlterModelOptions(
            name='allpaylog',
            options={'ordering': ['-date_action']},
        ),
        migrations.AlterModelOptions(
            name='alltimepaylog',
            options={'ordering': ['-date_add']},
        ),
        migrations.AlterModelOptions(
            name='invoiceforpayment',
            options={'ordering': ('date_create',), 'permissions': (('can_view_invoiceforpayment', 'Can view invoice for payment'),), 'verbose_name': 'Debt', 'verbose_name_plural': 'Debts'},
        ),
        migrations.AlterModelOptions(
            name='passportinfo',
            options={'verbose_name': 'Passport Info', 'verbose_name_plural': 'Passport Info'},
        ),
        migrations.AddField(
            model_name='alltimepaylog',
            name='abon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='abonapp.Abon'),
        ),
        migrations.AddField(
            model_name='alltimepaylog',
            name='receipt_num',
            field=models.IntegerField(default=0, verbose_name='Receipt number'),
        ),
        migrations.AddField(
            model_name='alltimepaylog',
            name='trade_point',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Trade point'),
        ),
        migrations.AlterField(
            model_name='abon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='abon',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonGroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='abon',
            name='house',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='House'),
        ),
        migrations.AlterField(
            model_name='abon',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonStreet', verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='abonlog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='additionaltelephone',
            name='telephone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+[7,8,9,3]\\d{10,11}$')], verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='extrafieldsmodel',
            name='field_type',
            field=models.CharField(choices=[('int', 'Digital field'), ('str', 'Text field'), ('dbl', 'Floating field'), ('ipa', 'Ip Address')], default='str', max_length=3),
        ),
        migrations.AddField(
            model_name='periodicpayforid',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='periodicpayforid',
            name='periodic_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff_app.PeriodicPay', verbose_name='Periodic pay'),
        ),
    ]
