# Generated by Django 2.1 on 2018-09-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0003_abon_nas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abon',
            options={'ordering': ('fio',), 'permissions': (('can_buy_tariff', 'Buy service perm'), ('can_add_ballance', 'fill account'), ('can_ping', 'Can ping')), 'verbose_name': 'Abon', 'verbose_name_plural': 'Abons'},
        ),
        migrations.AlterModelOptions(
            name='abonlog',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='additionaltelephone',
            options={'ordering': ('owner_name',), 'verbose_name': 'Additional telephone', 'verbose_name_plural': 'Additional telephones'},
        ),
        migrations.AlterModelOptions(
            name='invoiceforpayment',
            options={'ordering': ('date_create',), 'verbose_name': 'Debt', 'verbose_name_plural': 'Debts'},
        ),
        migrations.AddField(
            model_name='abon',
            name='autoconnect_service',
            field=models.BooleanField(default=False, verbose_name='Automatically connect next service'),
        ),
        migrations.AlterField(
            model_name='abon',
            name='is_dynamic_ip',
            field=models.BooleanField(default=False, verbose_name='Is dynamic ip'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='date_of_acceptance',
            field=models.DateField(verbose_name='Date of acceptance'),
        ),
    ]
