# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0003_abongroup_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abongroup',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='abon_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
