# Generated by Django 2.1 on 2018-09-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('abonapp', '0004_auto_20180918_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abon',
            name='current_tariff',
            field=models.OneToOneField(blank=True, default=None, null=True,
                                       on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonTariff'),
        ),
    ]
