# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-25 21:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0004_auto_20161220_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abon',
            options={'permissions': (('can_buy_tariff', 'Покупка тарифа абоненту'),)},
        ),
        migrations.AlterModelOptions(
            name='abongroup',
            options={'permissions': (('can_add_ballance', 'Пополнение счёта'),)},
        ),
        migrations.AlterModelOptions(
            name='abontariff',
            options={'ordering': ('tariff_priority',), 'permissions': (('can_complete_service', 'Досрочное завершение услуги абонента'), ('can_activate_service', 'Активация услуги абонента'))},
        ),
    ]
