# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 14:06
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abonapp', '0005_auto_20180123_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='abon',
            name='markers',
            field=bitfield.models.BitField((('icon_donkey', 'Donkey'), ('icon_fire', 'Fire'), ('icon_ok', 'Ok'),
                                            ('icon_king', 'King'), ('icon_tv', 'TV'), ('icon_smile', 'Smile'),
                                            ('icon_dollar', 'Dollar'), ('icon_service', 'Service'),
                                            ('icon_mrk', 'Marker')), default=None),
        ),
    ]
