# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 13:26
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0005_auto_20161226_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonStreets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.AbonGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='abon',
            name='address',
        ),
        migrations.AddField(
            model_name='abon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abon',
            name='house',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='abon',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonStreets'),
        ),
    ]
