# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 13:50
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0006_auto_20170128_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPayLog',
            fields=[
                ('pay_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('summ', models.FloatField(default=0.0)),
                ('pay_system_name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'all_pay_log',
                'ordering': ('date_action',),
            },
        ),
        migrations.CreateModel(
            name='AllTimePayLog',
            fields=[
                ('pay_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('summ', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'all_time_pay_log',
                'ordering': ('date_add',),
            },
        ),
        migrations.RenameModel(
            old_name='AbonStreets',
            new_name='AbonStreet',
        ),
    ]
