# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 21:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0007_auto_20170131_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonRawPassword',
            fields=[
                ('account', models.OneToOneField(primary_key=True, serialize=False, to='abonapp.Abon')),
                ('passw_text', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'abon_raw_password',
            },
        ),
        migrations.AlterModelTable(
            name='abonstreet',
            table='abon_street',
        ),
    ]
