# Generated by Django 2.1 on 2018-11-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0008_auto_20181115_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllPayLog',
        ),
    ]
