# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 13:30
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0009_abontariff_death_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFieldsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('int', 'Digital field'), ('str', 'Text field'), ('dbl', 'Floating field')], max_length=3)),
                ('data', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'abon_extra_fields',
            },
        ),
        migrations.AlterModelOptions(
            name='abon',
            options={'permissions': (('can_buy_tariff', 'Покупка тарифа абоненту'), ('can_view_passport', 'Can view passport'))},
        ),
        migrations.AlterModelOptions(
            name='abontariff',
            options={'ordering': ('tariff_priority',), 'permissions': (('can_complete_service', 'Снятие со счёта средств'), ('can_activate_service', 'Активация услуги абонента'))},
        ),
        migrations.AlterField(
            model_name='abon',
            name='ballance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='extrafieldsmodel',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='abonapp.Abon'),
        ),
    ]
