# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0010_auto_20170220_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abon',
            options={'permissions': (('can_buy_tariff', 'Покупка тарифа абоненту'), ('can_view_passport', 'Может просматривать паспортные данные'))},
        ),
        migrations.AlterField(
            model_name='extrafieldsmodel',
            name='field_type',
            field=models.CharField(choices=[('int', 'Цифровое поле'), ('str', 'Текстовое поле'), ('dbl', 'Дробное с плавающей точкой')], max_length=3),
        ),
    ]
