# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0011_auto_20170222_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafieldsmodel',
            name='account',
        ),
        migrations.AddField(
            model_name='abon',
            name='extra_fields',
            field=models.ManyToManyField(to='abonapp.ExtraFieldsModel'),
        ),
    ]
