# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_app', '0002_tariff_descr'),
        ('abonapp', '0012_auto_20170227_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='abongroup',
            name='tariffs',
            field=models.ManyToManyField(blank=True, related_name='tariff_groups', to='tariff_app.Tariff'),
        ),
    ]
