# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 11:52
from __future__ import unicode_literals

import django.db.models.deletion
import djing.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0013_abongroup_tariffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opt82',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', djing.fields.MACAddressField(integer=True)),
                ('port', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'opt_82',
            },
        ),
        migrations.AlterField(
            model_name='abon',
            name='extra_fields',
            field=models.ManyToManyField(blank=True, to='abonapp.ExtraFieldsModel'),
        ),
        migrations.AlterUniqueTogether(
            name='opt82',
            unique_together=set([('mac', 'port')]),
        ),
        migrations.AddField(
            model_name='abon',
            name='opt82',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonapp.Opt82'),
        ),
    ]
