# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0004_device_user_group'),
        ('abonapp', '0015_passportinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devapp.Device')),
            ],
            options={
                'db_table': 'abon_device',
            },
        ),
        migrations.AlterUniqueTogether(
            name='abondevice',
            unique_together=set([('abon', 'device')]),
        ),
    ]
