# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0017_auto_20170416_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abondevice',
            name='abon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon'),
        ),
        migrations.AlterField(
            model_name='abondevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.Device'),
        ),
    ]
