# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0021_auto_20170705_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abontariff',
            options={'permissions': (('can_complete_service', 'Снятие со счёта средств'),)},
        ),
        migrations.RemoveField(
            model_name='abon',
            name='current_tariffs',
        ),
        migrations.AddField(
            model_name='abon',
            name='current_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonTariff'),
        ),
        migrations.AlterUniqueTogether(
            name='abontariff',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='abontariff',
            name='abon',
        ),
        migrations.RemoveField(
            model_name='abontariff',
            name='tariff_priority',
        ),
    ]
