# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 00:20
from __future__ import unicode_literals

from django.db import migrations, models
from djing.fields import MyGenericIPAddressField
import statistics.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatCache',
            fields=[
                ('last_time', statistics.fields.UnixDateTimeField()),
                ('ip', MyGenericIPAddressField(max_length=8, primary_key=True, protocol='ipv4', serialize=False)),
                ('octets', models.PositiveIntegerField(default=0)),
                ('packets', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'flowcache',
            },
        ),
    ]
