# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 23:51
from __future__ import unicode_literals

from django.db import migrations, models

import mydefs


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', mydefs.MyGenericIPAddressField(max_length=8, protocol=b'IPv4')),
                ('dst_ip', mydefs.MyGenericIPAddressField(max_length=8, protocol=b'IPv4')),
                ('proto', models.PositiveSmallIntegerField(default=0)),
                ('src_port', models.PositiveIntegerField(default=0)),
                ('dst_port', models.PositiveIntegerField(default=0)),
                ('octets', models.PositiveIntegerField(default=0)),
                ('packets', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'flowstat',
            },
        ),
    ]
