# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatElem',
        ),
    ]
