# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import mydefs
import statistics.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatCache',
            fields=[
                ('last_time', statistics.fields.UnixDateTimeField()),
                ('ip', mydefs.MyGenericIPAddressField(max_length=8, primary_key=True, protocol='ipv4', serialize=False)),
                ('octets', models.PositiveIntegerField(default=0)),
                ('packets', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'flowcache',
            },
        ),
        migrations.DeleteModel(
            name='StatElem',
        ),
    ]
