# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models
from statistics.fields import UnixDateTimeField


class Migration(migrations.Migration):

    dependencies = [
        ('abonapp', '0002_auto_20180808_1448'),
        ('statistics', '0002_auto_20180808_1236'),
    ]

    operations = [
        migrations.DeleteModel('StatCache'),
        migrations.CreateModel(
            name='StatCache',
            fields=[
                ('last_time', UnixDateTimeField()),
                ('abon', models.OneToOneField(on_delete=models.deletion.CASCADE, primary_key=True, serialize=False, to='abonapp.Abon')),
                ('octets', models.PositiveIntegerField(default=0)),
                ('packets', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'flowcache',
            },
        )
    ]
