# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models
from statistics.fields import UnixDateTimeField


class Migration(migrations.Migration):
    dependencies = [
        ('abonapp', '0002_auto_20180808_1448'),
        ('statistics', '0002_auto_20180808_1236'),
    ]

    operations = [
        migrations.RunSQL(
            (
                "DROP TABLE `flowcache`;",
                "CREATE TABLE `flowcache` ( "
                "  `last_time` INT(10) UNSIGNED NOT NULL, "
                "  `abon_id`   INT(11) DEFAULT NULL UNIQUE, "
                "  `octets`    INT(10) UNSIGNED NOT NULL, "
                "  `packets`   INT(10) UNSIGNED NOT NULL, "
                "  KEY `flowcache_abon_id_91e1085d` (`abon_id`) "
                ") ENGINE = MEMORY  DEFAULT CHARSET = utf8;"
            ),
            state_operations=[
                migrations.DeleteModel(name='statcache'),
                migrations.CreateModel(
                    name='statcache',
                    fields=[
                        ('last_time', UnixDateTimeField()),
                        ('abon', models.OneToOneField('abonapp.Abon', on_delete=models.CASCADE, primary_key=True)),
                        ('octets', models.PositiveIntegerField(default=0)),
                        ('packets', models.PositiveIntegerField(default=0))
                    ],
                    options={
                        'db_table': 'flowcache',
                    },
                )
            ]
        )
    ]
